### PR TITLE
General update

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
Update Tox, GitHub actions, Python versions; see the individual commit messages for some more detail.

### CODE REVIEW

**Comment by legoktm** [comment]
Thank you, but I would like to stop maintaining this repo, I don't really use it anymore. I could transfer it to you (+pypi access) if you're interested, but also maybe we should make it collaboratively maintained on Wikimedia GitLab or something.

**Comment by lucaswerkmeister** [comment]
I think I’d be interested in (co-)maintaining it in principle – at least, I see myself still using Python on Toolforge in the near- and mid-term future (though that doesn’t mean I’m not also open to other options… Rust certainly looks interesting, and also given how much time I’ve put into [m3api](https://github.com/lucaswerkmeister/m3api/) you’d *think* I ought to use it in some JS tool :wink:). But while I’ve written a fair amount of Python code now, I’ve never written a proper library or put one on PyPI before.

**Comment by legoktm** [comment]
To close the loop for those following along here and not IRC, Both Lucas and @bd808 have access to this GH repo and PyPI - leaving it in their good hands now :-)

**Comment by lucaswerkmeister** [comment]
Indeed! Closing this PR – the new home is now [on GitLab](https://gitlab.wikimedia.org/toolforge-repos/python-toolforge) (compare [T333495](https://phabricator.wikimedia.org/T333495)), where @bd808 already repeated much of this PR.

**Pull request closed without merging**
